---

# Debian-family dependencies

- name: Ensure required packages
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - cron
    - curl
    - python-setuptools
    - python-pip
    - python-dev
    - libz-dev
    - libssl-dev
    - libjpeg-dev
    - libxslt1-dev
    - poppler-utils
    - lynx-cur
    - unzip
    - supervisor
    - git
    - wv

- name: Ensure recent python-virtualenv
  pip: name=virtualenv extra_args='--install-option="--install-scripts=/usr/local/bin"' state=latest
  # note that this installs to /usr/local/bin
  # which is not automatically on the path

- name: Set virtualenv path
  set_fact: virtualenv_path=/usr/local/bin/

- name: Ensure supervisor is started
  when: instance_config.plone_use_supervisor
  service: name=supervisor state=started enabled=yes

# As of 2016-04-12, Xenial is not getting enabled by service play above
- name: Set supervisor to start on boot in Xenial
  when: instance_config.plone_use_supervisor and ansible_distribution_release == 'xenial'
  shell: systemctl enable supervisor.service

