---

- src: https://github.com/cjsteel/ansible.plone_server.git
  version: 1.2.16
  name: plone.plone_server

- src: https://github.com/jnv/ansible-role-unattended-upgrades.git
  version: v1.3.0
  name: jnv.unattended-upgrades

- src: https://github.com/ANXS/hostname.git
  version: v1.1.0
  name: ANXS.hostname
