---

- name: Munin-Node package present
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - munin-node
    - perl-XML-Parser

- name: Enable munin-node to start on boot - CentOS
  service:
    name=munin-node
    enabled=yes
