---

- include: "{{ ansible_os_family }}.yml"

- name: Custom logwatch files present
  copy:
    src=etc_logwatch/
    dest=/etc/logwatch/
    owner=root
    group=root

- name: Plone Events logwatch configuration
  template:
    src=plone_events.j2
    dest=/etc/logwatch/conf/services/plone_events.conf
    owner=root
    group=root

- name: Ignore log lines configuration
  copy:
    dest: /etc/logwatch/conf/ignore.conf
    content: "{{ logwatch_ignore }}"
    mode: 0644
    owner: root
    group: root


- name: Add update notify to logwatch
  template:
    src=update-notify.j2
    dest=/etc/logwatch/scripts/services/update-notify
    owner=root
    group=root
    mode=0755
  when: ansible_os_family == 'Debian'
